devices:
  - address: 10.0.0.1
    username: prometheus
    password: prometheus
    features:
      power: true
      threads: true
      subnets: true
      dns: true
      dhcp: true
      profiles: true
      pppoe: true
      l2tp: true
      sessions: true
